InvoiceProject:
  dbConfig:
    host: localhost
    user: root
    password: root
    port: 3306
    dbName: invoice_db
  apiConfig:
    secret: thatsmysecret
    user: apiuser
    password: apipassword
  nodeServer:
    host: localhost
    port: 3000